import { useUserInfo } from "@/context/userContext";

const Profile = () => {
  const { userInfo } = useUserInfo();
  const fullName = `${userInfo?.name} ${userInfo?.lastName}`;
  const formattedDate = userInfo
    ? new Date(userInfo?.createdAt).toDateString()
    : "";
  return (
    <main className=" px-5 h-[91vh] bg-zinc-100">
      <div className=" flex flex-col md:flex-row justify-evenly md:justify-around items-center h-full w-full min-w-[320px]">
        <section className=" flex flex-col justify-center items-center gap-y-2 md:w-1/2">
          <img
            className="w-52 bg-slate-600 rounded-full "
            src="https://xsgames.co/randomusers/avatar.php?g=male"
            alt="avatar-picture"
          />
          <span className=" font-thin text-xs w-full text-center text-gray-500">
            *Random user photo generated by{" "}
            <a className=" underline" href="https://xsgames.co/randomusers/">
              https://xsgames.co/randomusers/
            </a>
          </span>
        </section>
        <section className=" md:w-1/2 flex items-center flex-col justify-center gap-y-3">
          <div className=" text-center">
            <h3 className=" font-semibold text-2xl ">Full Name</h3>
            <p className=" font-extralight">{fullName}</p>
          </div>
          <div className=" text-center">
            <h3 className=" font-semibold text-2xl">Email</h3>
            <p className=" font-extralight">{userInfo?.email}</p>
          </div>
          <div className=" text-center">
            <h3 className=" font-semibold text-2xl">Date of Count Creation</h3>
            <p className=" font-extralight">{formattedDate}</p>
          </div>
        </section>
      </div>
    </main>
  );
};
export default Profile;
